---
name: 改进现有功能
about: 改进部分现有功能
title: "[improve]: "
labels: '功能请求'
assignees: ''

---

**此改进是否与某个问题有关？请描述。**  
请清楚且简洁地说明目前存在的问题。例如：不给我下载链接

**请描述你希望的解决方案**  
请清楚且简洁地说明你希望实现的功能或预期效果。

**请描述你曾考虑过的替代方案**  
请清楚且简洁地说明你曾考虑过的其他解决方法或替代功能。

**其他补充说明**  
请在此补充任何相关背景资讯、使用情境或截图等。
